catalog:
  dotenv: ^17.3.1
catalogMode: prefer

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract

overrides:
  typescript: 5.8.2

shellEmulator: true

trustPolicy: no-downgrade
